=== Arelle/Arelle/tests/conformance/XDT-CONF-CR4-2009-10-06/lib/test.xsd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by TestXMLSpy (My Comp) --><!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)--><xs:schema xmlns:conf="http://xbrl.org/2005/conformance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xbrldt="http://xbrl.org/2005/xbrldt" targetNamespace="http://xbrl.org/2005/conformance" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="inputFileType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="readMeFirst" type="xs:boolean" use="optional" default="false"/>
				<xs:attribute name="schemavalid" type="xs:boolean" use="optional" default="true"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="xsd" type="conf:inputFileType"/>
	<xs:element name="linkbase" type="conf:inputFileType"/>
	<xs:element name="instance" type="conf:inputFileType"/>
	<xs:element name="data">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="conf:xsd"/>
				<xs:element ref="conf:linkbase"/>
				<xs:element ref="conf:instance"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="result" type="conf:resultListType">
		<xs:annotation>
			<xs:documentation>The result of a test is a list of errors, warnings and inconsistencies</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="resultListType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element ref="conf:file"/>
			<xs:element ref="conf:error"/>
			<xs:element ref="conf:warning"/>
			<xs:element ref="conf:inconsistency"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="file" type="xs:anyURI"/>
	<xs:element name="error" type="xs:QName"/>
	<xs:element name="warning" type="xs:QName"/>
	<xs:element name="inconsistency" type="xs:QName"/>
	<xs:element name="description">
		<xs:complexType mixed="true">
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="referenceURI" type="xs:anyURI" use="optional"/>
					<xs:attribute name="reference" type="conf:referenceType" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="referenceType">
		<xs:annotation>
			<xs:documentation>This is a reference to a title in a document. The pattern is of the form "filename#1.2.3"</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value=".*#([0-9])+(\.[0-9]+)*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="variation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="conf:description"/>
				<xs:element ref="conf:data"/>
				<xs:element ref="conf:result"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="testcase">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="conf:variation" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="outpath" type="xs:string" use="required"/>
			<xs:attribute name="owner" type="xs:string" use="required"/>
			<xs:attribute name="minimal" type="xs:boolean" use="optional" default="true"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Arelle/Arelle/tests/conformance/XBRL-CONF-CR4-2008-07-02/Common/linkbase/232-ArcsUsingNonCanonicalDecimal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2008 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Syntactically equal arcs" description="S-Equal attributes must have X-equal values.  Attributes with schema types of decimal might not have the same lexical representation, yet still be X-equal." outpath="out" owner="walter@hamscher.com" xsi:noNamespaceSchemaLocation="../lib/test.xsd" minimal="true">
	
	<variation id="V-01" name="232-01-ArcsUsingNonCanonicalDecimalOrderInconsistent">
		<description>S-Equal attributes must have X-equal values.  Attributes with schema types of decimal might not have the same lexical representation and still be X-equal.  This test case must raise a calculation inconsistency. If a calculation inconsistency is NOT found then the processor has failed because decimal "1.0" is x-equal to decimal "+1"; it has failed to prohibit an arc that should be prohibited.</description>
		<data>
			<instance readMeFirst="true">232-01-ArcsUsingNonCanonicalDecimalOrderInconsistent.xbrl</instance>
		</data>
		<result expected="invalid"></result>
	</variation>
		
	<variation id="V-02" name="232-02-ArcsUsingNonCanonicalDecimalOrderConsistent">
		<description>S-Equal attributes must have X-equal values.  Attributes with schema types of decimal might not have the same lexical representation and still be X-equal.  This test case must NOT raise a calculation inconsistency. If a calculation inconsistency is found then the processor has failed because decimal "1.0" is x-equal to decimal "+1"; it has failed to prohibit an arc that should be prohibited.</description>
		<data>
			<instance readMeFirst="true">232-02-ArcsUsingNonCanonicalDecimalOrderConsistent.xbrl</instance>
		</data>
		<result expected="valid"></result>
	</variation>
	
		<variation id="V-03" name="232-03-ArcsUsingNonCanonicalDecimalWeightInconsistent">
		<description>S-Equal attributes must have X-equal values.  Attributes with schema types of decimal might not have the same lexical representation and still be X-equal.  This test case must raise a calculation inconsistency. If a calculation inconsistency is NOT found then the processor has failed because decimal "1.0" is x-equal to decimal "+1"; it has failed to prohibit an arc that should be prohibited.</description>
		<data>
			<instance readMeFirst="true">232-03-ArcsUsingNonCanonicalDecimalWeightInconsistent.xbrl</instance>
		</data>
		<result expected="invalid"></result>
	</variation>
		
	<variation id="V-04" name="232-04-ArcsUsingNonCanonicalDecimalWeightConsistent">
		<description>S-Equal attributes must have X-equal values.  Attributes with schema types of decimal might not have the same lexical representation and still be X-equal.  This test case must NOT raise a calculation inconsistency. If a calculation inconsistency is found then the processor has failed because decimal "1.0" is x-equal to decimal "+000001.0000000"; it has failed to prohibit an arc that should be prohibited.</description>
		<data>
			<instance readMeFirst="true">232-04-ArcsUsingNonCanonicalDecimalWeightConsistent.xbrl</instance>
		</data>
		<result expected="valid"></result>
	</variation>

</testcase>

=== Arelle/Arelle/tests/conformance/XBRL-CONF-CR4-2008-07-02/Common/linkbase/210-relationshipEquivalence.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Relationship Equivalence" outpath="out" owner="cps@decisionsoft.com" minimal="false" description="Checks that relationship equivalence is correctly evaluated." xsi:noNamespaceSchemaLocation="../lib/test.xsd">
	<!-- Tests that relationship equivalence is correct -->
	<variation id="V-1" name="Two calculation arcs are equivalent.">
		<description>210.01 A prohibiting arc of a higher priority overrides a relationship, thus removing the calculation relationship.  The instance would be invalid if the relationship had not been prohibited.</description>
		<data>
			<xsd readMeFirst="false">210-01-RelationshipEquivalence.xsd</xsd>
			<linkbase readMeFirst="false">210-01-RelationshipEquivalence-calculation-1.xml</linkbase>
			<linkbase readMeFirst="false">210-01-RelationshipEquivalence-calculation-2.xml</linkbase>
			<instance readMeFirst="true">210-01-RelationshipEquivalence-instance.xml</instance>
		</data>
		<result expected="valid">210-01-RelationshipEquivalence-instanceOut.xml</result>
	</variation>
	<variation id="V-2" name="Two calculation arcs are not equivalent (differing order).">
		<description>210.02 A prohibiting arc of a higher priority has a different order to another arc and thus fails to prohibit the said arc.  The instance is thus invalid since it doesn't add up.</description>
		<data>
			<xsd readMeFirst="false">210-02-DifferentOrder.xsd</xsd>
			<linkbase readMeFirst="false">210-02-DifferentOrder-calculation-1.xml</linkbase>
			<linkbase readMeFirst="false">210-02-DifferentOrder-calculation-2.xml</linkbase>
			<instance readMeFirst="true">210-02-DifferentOrder-instance.xml</instance>
		</data>
		<result expected="invalid"/>
	</variation>
	<variation id="V-3" name="Two calculation arcs are equivalent (default order).">
		<description>210.03 A prohibiting arc of a higher priority has no order attribute, and another arc has order one.  The instance is thus valid since the arc is prohibited as the prohibiting arc's order takes the default value.</description>
		<data>
			<xsd readMeFirst="false">210-03-MissingOrder.xsd</xsd>
			<linkbase readMeFirst="false">210-03-MissingOrder-calculation-1.xml</linkbase>
			<linkbase readMeFirst="false">210-03-MissingOrder-calculation-2.xml</linkbase>
			<instance readMeFirst="true">210-03-MissingOrder-instance.xml</instance>
		</data>
		<result expected="valid">210-03-MissingOrder-instanceOut.xml</result>
	</variation>
</testcase>

=== Arelle/Arelle/tests/conformance/XBRL-CONF-CR4-2008-07-02/Common/linkbase/220-NonStandardArcsAndTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Non-standard Embedded Linkbases" description="Non-standard Embedded linkbases" outpath="out" owner="dws@decisionsoft.com" xsi:noNamespaceSchemaLocation="../lib/test.xsd" minimal="true">
	
	<variation id="V-01" name="220-01-NonStandardArcroleCycle.xsd">
		<description>A cycle between arcs in a non-core extended link, and non-core arcs.</description>
		<data>
			<xsd readMeFirst="true">220-01-NonStandardArcrole.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>
	
	<variation id="V-02" name="220-02-NonStandardArcWithUndefinedArcrole.xsd">
		<description>Cycle in custom arc with arcrole URI that isnt defined in an arcroleRef or arcroleType. Cycles should be OK.</description>
		<data>
			<xsd readMeFirst="true">220-02-NonStandardArcWithUndefinedArcrole.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>

	<variation id="V-03" name="220-03-CycleInUnreferencedArcrole.xsd">
		<description>ArcroleType and linkbase in same file, linkbase doesnt reference arcroleType which prohibits cycles. We have a cycle.</description>
		<data>
			<xsd readMeFirst="true">220-03-CycleInUnreferencedArcrole.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>

	<variation id="V-04" name="220-04-StandardArcWithUnreferencedArcrole.xsd">
		<description>Arcrole defined in same file as linkbase where it is used, but with no arcroleRef. Should require arcroleRef.</description>
		<data>
			<xsd readMeFirst="true">220-04-StandardArcWithUnreferencedArcrole.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>
  
	<variation id="V-05" name="220-05-UsedOnSignificanceOnCustomArc.xsd">
		<description>Custom arcrole type with usedOn of presentationArc. Referenced and used on a non-standard arc. Should get error according to 5.1.4.5.</description>
		<data>
			<xsd readMeFirst="true">220-05-UsedOnSignificanceOnCustomArc.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>

	<variation id="V-06" name="220-06-Change of error depending on DTS">
		<description>Individually linkbases are valid, but putting them together is undefined. Should we report the cycles?</description>
		<data>
			<xsd readMeFirst="true">220-06-Taxonomy.xsd</xsd>
	    <linkbase readMeFirst="false">220-06-Linkbase1.xml</linkbase>
	    <linkbase readMeFirst="false">220-06-Linkbase2.xml</linkbase>
			<xsd readMeFirst="false">220-06-Concepts.xsd</xsd>
			<xsd readMeFirst="false">220-06-Arcrole.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>

	<variation id="V-07" name="220-07-Change of error depending on DTS">
		<description>Test of just linkbase1. It has the cycle, but no arcrole ref.</description>
		<data>
	    <linkbase readMeFirst="true">220-06-Linkbase1.xml</linkbase>
			<xsd readMeFirst="false">220-06-Concepts.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>

	<variation id="V-08" name="220-08-Change of error depending on DTS">
		<description>Test of just linkbase1. It has the cycle, but no arcrole ref. Yet we add the arcrole type definition to the DTS.</description>
		<data>
			<xsd readMeFirst="true">220-08-Taxonomy.xsd</xsd>
	    <linkbase readMeFirst="false">220-06-Linkbase1.xml</linkbase>
			<xsd readMeFirst="false">220-06-Concepts.xsd</xsd>
			<xsd readMeFirst="false">220-06-Arcrole.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>

  
	
</testcase>

=== Arelle/Arelle/tests/conformance/XBRL-CONF-CR4-2008-07-02/Common/linkbase/211-Testcase-sEqualUsedOn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XBRL 2.1 Tests -->
<!-- Copyright 2003 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?>
<testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  name="sEqualUsedOn" 
  description="5.1.3.4 - Within a roleType element there MUST NOT be s-equal usedOn elements." 
  outpath="out" 
  owner="mrg@decisionsoft.com" 
  minimal="true"
  xsi:noNamespaceSchemaLocation="../lib/test.xsd" >

  <!-- 
    NOTE: The definition of s-equal for usedOn was modified by erratum 041.
    Variations 02 and 03 test the change.
  -->

	<variation id="V-00" name="NonSEqualUsedOn">
		<description>
      A valid roleType.  usedOn elements refer to different elements in the
      same namespace.
    </description>
		<data>
			<xsd readMeFirst="true">211-00-NonSEqualUsedOn-valid.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>

	<variation id="V-01" name="SEqualUsedOnSamePrefixSameNamespace">
		<description>
      Simple invalid roleType.  usedOn elements refer to the same element
      twice.
      
      QName content of the two usedOn elements is lexically identical AND equal
      in the QName value space (same prefix, same namespace, same local name).
    </description>
		<data>
			<xsd readMeFirst="true">211-01-SEqualUsedOnSamePrefixSameNamespace-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>

	<variation id="V-02" name="SEqualUsedOnDifferentPrefixesSameNamespace">
    <description>
      roleType invalid according to erratum 041.  usedOn elements refer to the
      same element twice.
      
      QName content of the two usedOn elements is lexically different, but
      equal in the QName value space (prefixes are different, but both prefixes
      are bound to the same namespace).
    </description> 
    <data>
			<xsd readMeFirst="true">211-02-SEqualUsedOnDifferentPrefixesSameNamespace-invalid.xsd</xsd>
		</data>
		<result expected="invalid"/>
	</variation>

	<variation id="V-03" name="NonSEqualUsedOnSamePrefixDifferentNamespaces">
		<description>
      roleType that is valid according to erratum 041.  usedOn elements refer
      to elements that have the same local name but different namespaces.
      
      QName content of the two usedOn elements is lexically identical but
      distinct in the QName value space (prefixes are the same, but each prefix
      is bound to a different namespace).
    </description>
		<data>
			<xsd readMeFirst="true">211-03-NonSEqualUsedOnSamePrefixDifferentNamespaces-valid.xsd</xsd>
		</data>
		<result expected="valid"/>
	</variation>

</testcase>

=== Arelle/Arelle/tests/conformance/Formula-CONF-REC-PER-Errata-2011-03-16/REC-PER-Errata-testcases-2011-03-16/tests/10000 Formula/11062-Formula-StaticAnalysis-OCC-missingSAVForDimensionRule/11062-OCC-missingSAVForDimensionRule_testcase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2007 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../../infrastructure/test.xsl"?>
<testcase
xmlns="http://xbrl.org/2008/conformance"
xmlns:xbrlfe="http://xbrl.org/2008/formula/error"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="
  http://xbrl.org/2008/conformance 
  ../../../infrastructure/test.xsd">
  <creator>
    <name>Pablo Navarro Salvador, Herm Fischer</name>
    <email>pns.atos@gmail.com, fischer@markv.com</email>
  </creator>
  <number>11062</number>
  <name>Open Context Component (OCC) rules in formulae. </name>
  <description>
    Formula Static Analysis Test.
    An error must be thrown if an dimension 
    rule does not have any child elements 
    and does not have a SAV for the dimension 
    that it identifies with its @dimension attribute.
  </description>
  <reference specification="FORMULA" id="sec-dimension-rules"/>
  <variation id="V-01">
    <description>
      The explicit dimension rule does not have any child elements
      and does not have a SAV for the dimension 
      that it identifies with its @dimension attribute
    </description>
  <reference specification="FORMULA" id="error-missing-sav-for-explicit-dimension-rule"/>
    <data>
      <schema readMeFirst="true">11062-v01-OCCdim-tests.xsd</schema>
      <linkbase>11062-v01-OCCdim-tests-definition.xml</linkbase>
      <linkbase>11062-v01-OCCdim-tests-formula.xml</linkbase>
    </data>
    <result>
      <error>xbrlfe:missingSAVForExplicitDimensionRule</error>
    </result>
  </variation>

  <variation id="V-02">
    <description>
      The typed dimension rule does not have any child elements
      and does not have a SAV for the dimension 
      that it identifies with its @dimension attribute
    </description>
  <reference specification="FORMULA" id="error-missing-sav-for-typed-dimension-rule"/>
    <data>
      <schema readMeFirst="true">11062-v02-OCCdim-tests.xsd</schema>
      <linkbase>11062-v02-OCCdim-tests-definition.xml</linkbase>
      <linkbase>11062-v02-OCCdim-tests-formula.xml</linkbase>
    </data>
    <result>
      <error>xbrlfe:missingSAVForTypedDimensionRule</error>
    </result>
  </variation>


</testcase>

=== Arelle/Arelle/tests/conformance/XDT-CONF-CR4-2009-10-06/100-xbrldte/116-DomainMemberSourceError/116-TestCase-DomainMemberSourceError.xml
<?xml version="1.0" encoding="UTF-8"?><!-- Copyright 2005 XBRL International. All Rights Reserved. --><?xml-stylesheet type="text/xsl" href="../../testcase.xsl"?><testcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xbrldte="http://xbrl.org/2005/xbrldt/errors" xmlns="http://xbrl.org/2005/conformance" name="116-TestCase-DomainMemberSourceError" description="2.1 to 2.10 - Dimensional relationships except 2.5" outpath="out" owner="ihr@xbrl.org" minimal="true" xsi:schemaLocation="http://xbrl.org/2005/conformance ../../lib/test.xsd">
        <!-- Dimensional taxonomy syntax rules pertaining to schemas and linkbases, and not covered by XML Schema and XBRL Validation. -->
        <!-- Note that XBRL validation requires the source and target of a definitionArc to be a concept. -->
        <!-- As of the 2005-10-26 internal working draft. (Herm) -->
        <!-- domainMember valid is same as dimensionDomainValid -->
        <!-- 2.5.3.1  1. A dimensional processor MUST raise an error [Dim Err, 19] xbrldte:DomainMemberSourceError if the source of a domain-member arc is not a primary item declaration -->
        <variation id="V-01" name="sourceDomainMemberIsDimensionInvalid">
                <description reference="XDT-IWD-2005-10-26.doc#2.5.3.1.1">The source of a domain-member relationship is a dimension item declaration, not a primary item.</description>
                <data>
                        <xsd readMeFirst="true">sourceDomainMemberIsDimensionInvalid.xsd</xsd>
                        <linkbase readMeFirst="false">sourceDomainMemberIsDimensionInvalid-definition.xml</linkbase>
                        <linkbase readMeFirst="false">sourceDomainMemberIsDimensionInvalid-label.xml</linkbase>
                </data>
                <result >
                        <error>xbrldte:DomainMemberSourceError</error>
                </result>
        </variation>
        <variation id="V-02" name="sourceDomainMemberIsHypercubeInvalid">
                <description reference="XDT-IWD-2005-10-26.doc#2.5.3.1.1">The source of a domain-member relationship is a hypercube item declaration, not a primary item.</description>
                <data>
                        <xsd readMeFirst="true">sourceDomainMemberIsHypercubeInvalid.xsd</xsd>
                        <linkbase readMeFirst="false">sourceDomainMemberIsHypercubeInvalid-definition.xml</linkbase>
                        <linkbase readMeFirst="false">sourceDomainMemberIsHypercubeInvalid-label.xml</linkbase>
                </data>
                <result >
                        <error>xbrldte:DomainMemberSourceError</error>
                </result>
        </variation>
</testcase>

=== Arelle/Arelle/tests/conformance/Formula-CONF-REC-PER-Errata-2011-03-16/REC-PER-Errata-testcases-2011-03-16/tests/30000 Assertions/31130-ConsistencyAssertion-StaticAnalysis-variablesNotAllowed/31130 Consistency Assertion Variables Not Allowed.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2007 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../../infrastructure/test.xsl"?>
<testcase
xmlns="http://xbrl.org/2008/conformance"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="
  http://xbrl.org/2008/conformance 
  ../../../infrastructure/test.xsd">
  <creator>
    <name>Herm Fischer</name>
    <email>fischer@markv.com</email>
  </creator>
  <number>31130</number>
  <name>Consistency Assertion Disallowed Variables</name>
  <description>
    Consistency check static analysis for disallowed variables.
  </description>
  <reference specification="CONSISTENCY-ASSERTION" id="error-variables-not-allowed"/>         

  <variation id="V-01">
    <name>Disallowed fact variable</name>
    <description>
      Superfluous disallowed fact variable related to the consistency assertion.  (Valid cases in 32210 test cases directory.)
    </description>
  <reference specification="CONSISTENCY-ASSERTION" id="error-variables-not-allowed"/>         
    <data>
      <schema>31130-consistencyAssertion-concepts.xsd</schema>
      <linkbase>31130-disallowedFactVariable-formula.xml</linkbase>
      <instance readMeFirst="true">31130-disallowedFactVariable-instance.xml</instance>
    </data>
    <result>
      <error xmlns:xbrlcae="http://xbrl.org/2008/assertion/consistency/error">
          xbrlcae:variablesNotAllowed 
      </error>
    </result>
  </variation>

  <variation id="V-02">
    <name>Disallowed general variable</name>
    <description>
      Superfluous disallowed general variable related to the consistency assertion.  (Valid cases in 32210 test cases directory.)
    </description>
  <reference specification="CONSISTENCY-ASSERTION" id="error-variables-not-allowed"/>         
    <data>
      <schema>31130-consistencyAssertion-concepts.xsd</schema>
      <linkbase>31130-disallowedGeneralVariable-formula.xml</linkbase>
      <instance readMeFirst="true">31130-disallowedGeneralVariable-instance.xml</instance>
    </data>
    <result>
      <error xmlns:xbrlcae="http://xbrl.org/2008/assertion/consistency/error">
          xbrlcae:variablesNotAllowed 
      </error>
    </result>
  </variation>


</testcase>
