=== Arelle/Arelle/tests/conformance/XDT-CONF-CR4-2009-10-06/lib/test.xsd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by TestXMLSpy (My Comp) --><!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)--><xs:schema xmlns:conf="http://xbrl.org/2005/conformance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xbrldt="http://xbrl.org/2005/xbrldt" targetNamespace="http://xbrl.org/2005/conformance" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="inputFileType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="readMeFirst" type="xs:boolean" use="optional" default="false"/>
				<xs:attribute name="schemavalid" type="xs:boolean" use="optional" default="true"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="xsd" type="conf:inputFileType"/>
	<xs:element name="linkbase" type="conf:inputFileType"/>
	<xs:element name="instance" type="conf:inputFileType"/>
	<xs:element name="data">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="conf:xsd"/>
				<xs:element ref="conf:linkbase"/>
				<xs:element ref="conf:instance"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="result" type="conf:resultListType">
		<xs:annotation>
			<xs:documentation>The result of a test is a list of errors, warnings and inconsistencies</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="resultListType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element ref="conf:file"/>
			<xs:element ref="conf:error"/>
			<xs:element ref="conf:warning"/>
			<xs:element ref="conf:inconsistency"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="file" type="xs:anyURI"/>
	<xs:element name="error" type="xs:QName"/>
	<xs:element name="warning" type="xs:QName"/>
	<xs:element name="inconsistency" type="xs:QName"/>
	<xs:element name="description">
		<xs:complexType mixed="true">
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="referenceURI" type="xs:anyURI" use="optional"/>
					<xs:attribute name="reference" type="conf:referenceType" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="referenceType">
		<xs:annotation>
			<xs:documentation>This is a reference to a title in a document. The pattern is of the form "filename#1.2.3"</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value=".*#([0-9])+(\.[0-9]+)*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="variation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="conf:description"/>
				<xs:element ref="conf:data"/>
				<xs:element ref="conf:result"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="testcase">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="conf:variation" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
			<xs:attribute name="outpath" type="xs:string" use="required"/>
			<xs:attribute name="owner" type="xs:string" use="required"/>
			<xs:attribute name="minimal" type="xs:boolean" use="optional" default="true"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Arelle/Arelle/tests/conformance/Formula-CONF-REC-PER-Errata-2011-03-16/REC-PER-Errata-testcases-2011-03-16/tests/20000 Variables/22090-Variable-Processing-VariableSetRelationships/22090 Variable Set Relationship.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2007 XBRL International. All Rights Reserved. -->
<?xml-stylesheet type="text/xsl" href="../../../infrastructure/test.xsl"?>
<testcase
  xmlns="http://xbrl.org/2008/conformance"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xbrl.org/2008/conformance ../../../infrastructure/test.xsd"
  xmlns:xbrlfe="http://xbrl.org/2008/formula/error"
  xmlns:binding="http://xbrl.org/2008/binding/errors"
  xmlns:label="http://xbrl.org/2008/label/error"
  xmlns:reference="http://xbrl.org/2008/reference/error"  
  >
  <creator>
    <name>Herm Fischer</name>
    <email>fischer@markv.com</email>
  </creator>
  <number>22090</number>
  <name>Variable set relationship processing tests</name>
  <description>
    Tests of variable set relationship processing, including use of name parameter on relationship independent of shared or named situation of its source or target resources
  </description>
  <reference specification="VARIABLES" id="sec-variable-set-relationships"/>

  <variation id="V-01">
    <name>Variable name independent of formula and sharing</name>
    <description>Tests that a variable's name, given by the arc, is independent of shared nature of variable.  Three formulas share variable but give it different names on each arc.</description>
    <reference specification="VARIABLES" id="sec-variable-set-relationships"/>
    <data>
      <schema>22090-variableSetRelationship-tests.xsd</schema>
      <linkbase>22090-sharedVariablesDiffNames-formula.xml</linkbase>
      <instance readMeFirst="true">22090-sharedVariablesDiffNames-instance.xml</instance>
    </data>
    <result>
      <instance>22090-sharedVariablesDiffNames-result.xml</instance>
    </result>
  </variation>  

  <variation id="V-02">
    <name>Parameter referencing name independent of the parameter declaration</name>
    <description>Tests that the name given on the arc is used to access the parameter in a formula, which is independent of the name given the parameter in its resource declaration.</description>
    <reference specification="VARIABLES" id="sec-variable-set-relationships"/>
    <data>
      <schema>22090-variableSetRelationship-tests.xsd</schema>
      <linkbase>22090-paramNameIsNotVarName-formula.xml</linkbase>
      <instance readMeFirst="true">22090-paramNameIsNotVarName-instance.xml</instance>
    </data>
    <result>
      <instance>22090-paramNameIsNotVarName-result.xml</instance>
    </result>
  </variation>  

  <variation id="V-03">
    <name>Arc references parameter from another linkbase file of parameter resources</name>
    <description>Based on V-02, tests that the parameter resource of the variable-set arc can be in a separate file which has just parameter resource(s).  A link:loc is used to "discover" the other linkbase file and retrieve the resource by an id.  The label on the parameter in the other file is set to "dummy" to demonstrate that its id, not its label, is used by the loc to find it.</description>
    <reference specification="VARIABLES" id="sec-variable-set-relationships"/>
    <data>
      <schema>22090-variableSetRelationship-tests.xsd</schema>
      <linkbase>22090-paramInAnotherFile-formula.xml</linkbase>
      <linkbase>22090-paramInAnotherFile-formula-params.xml</linkbase>
      <instance readMeFirst="true">22090-paramInAnotherFile-instance.xml</instance>
    </data>
    <result>
      <instance>22090-paramNameIsNotVarName-result.xml</instance>
    </result>
  </variation>  

  <variation id="V-04">
    <name>Arcs and resources in separate extended links of same linkbase file</name>
    <description>Based on V-01, tests that a variable-set arcs and resources can be separated to independent extended links, each of its own role name, all in the same linkbase file.
    </description>
    <reference specification="VARIABLES" id="sec-variable-set-relationships"/>
    <data>
      <schema>22090-variableSetRelationship-tests.xsd</schema>
      <linkbase>22090-separateExtLinks-formula.xml</linkbase>
      <instance readMeFirst="true">22090-separateExtLinks-instance.xml</instance>
    </data>
    <result>
      <instance>22090-sharedVariablesDiffNames-result.xml</instance>
    </result>
  </variation>  

  <variation id="V-05">
    <name>Arcs and resources in separate linkbase files</name>
    <description>Based on V-04, tests that a discovering loc can get variable-set arcs from a separate linkbase file of just arcs (discovered by just a loc in the linkbaseRef'ed linkbase file), 
and resources can be separated to another loc-discovered file of just resources.  So the discovery order is that the instance, 22090-separateLbFiles-instance.xml, linkbaseRef's to 22090-separateLbFiles-formula-loc.xml, which has only a discovery-causing loc (per XBRL 2.1 section 3.2), that discovers the linkbase file 22090-separateLbFiles-formula-arcs.xml, that has all of the arcs from V-04 above, each of which has a locs to its resources causing discovery of 22090-separateLbFiles-formula-resources.xml, which has the resources for these arcs.
    </description>
    <reference specification="VARIABLES" id="sec-variable-set-relationships"/>
    <data>
      <schema>22090-variableSetRelationship-tests.xsd</schema>
      <linkbase>22090-separateLbFiles-formula-loc.xml</linkbase>
      <linkbase>22090-separateLbFiles-formula-arcs.xml</linkbase>
      <linkbase>22090-separateLbFiles-formula-resources.xml</linkbase>
      <instance readMeFirst="true">22090-separateLbFiles-instance.xml</instance>
    </data>
    <result>
      <instance>22090-sharedVariablesDiffNames-result.xml</instance>
    </result>
  </variation>  

</testcase>
